version: '3'

services:
  springboot:
    container_name: springboot
    env_file:
      - /home/***/.env
    image: "${DOCKERHUB_USERNAME}/${APP_NAME}:latest"
    ports:
      - "8080:8080"
    networks:
      - myoungari

networks:
  myoungari: